# Generated by Django 4.2.7 on 2023-11-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_offersdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='offerDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('brand', models.TextField()),
                ('domain', models.TextField()),
                ('discount', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='offersDB',
        ),
    ]
