# Generated by Django 4.2.7 on 2023-11-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_dailyexpenses_delete_dailyexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('Client_Id', models.TextField()),
                ('brand', models.TextField()),
                ('domain', models.TextField()),
                ('payment_date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='dailyExpenses',
        ),
    ]
