# Generated by Django 4.2.7 on 2023-11-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_dailyexpense_delete_dailyexpenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default=None, max_length=250, null=True, upload_to='media')),
            ],
        ),
    ]
