# Generated by Django 4.2.7 on 2023-11-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageDB',
        ),
    ]
