# Generated by Django 4.2.7 on 2023-11-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_image_imagedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('dependents', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('cibil', models.IntegerField()),
                ('married', models.TextField()),
                ('credit_history', models.TextField()),
                ('savings', models.IntegerField()),
            ],
        ),
    ]
