# Generated by Django 4.2.7 on 2023-11-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_customers_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.TextField()),
                ('name', models.TextField()),
                ('verified', models.TextField()),
            ],
        ),
    ]
