# Generated by Django 4.2.7 on 2023-11-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_loandbs_delete_loandb'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number', models.TextField()),
                ('email', models.TextField()),
                ('age', models.IntegerField()),
                ('marital', models.IntegerField()),
                ('education', models.IntegerField()),
                ('dfault', models.IntegerField()),
                ('housing', models.IntegerField()),
                ('loan', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('day', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('campaign', models.IntegerField()),
                ('pdays', models.IntegerField()),
                ('previous', models.IntegerField()),
            ],
        ),
    ]
